# Generated by Django 3.2 on 2024-05-17 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jumia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartphone',
            old_name='bbrand',
            new_name='brand',
        ),
    ]
