# Generated by Django 3.2 on 2024-05-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jumia', '0002_rename_bbrand_smartphone_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='price',
            field=models.FloatField(),
        ),
    ]
